// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0As09t1YupqowL0oAuk_eHxArnMrUamw',
    appId: '1:790940087690:web:8087165be6be72c0e34473',
    messagingSenderId: '790940087690',
    projectId: 'smart-heart-6946f',
    authDomain: 'smart-heart-6946f.firebaseapp.com',
    storageBucket: 'smart-heart-6946f.appspot.com',
    measurementId: 'G-VDJNV2RDPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLx_GlAy58-ji8O1vrmnnOggPl1FjTy-c',
    appId: '1:790940087690:android:0646a73c1b8c6605e34473',
    messagingSenderId: '790940087690',
    projectId: 'smart-heart-6946f',
    storageBucket: 'smart-heart-6946f.appspot.com',
  );
}
